[tool.poetry]
name = "q1"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pymodbus = "^3.6.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
